-- Generated: 2026-01-27
-- Dialect: PostgreSQL (largely SQLite-compatible)
CREATE TABLE IF NOT EXISTS companies (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  industry TEXT,
  website_url TEXT,
  careers_url TEXT,
  it_tech_relevance BOOLEAN
);
INSERT INTO companies (name, industry, website_url, careers_url, it_tech_relevance) VALUES
('AB Enzymes Finland Oy','Biotech','https://www.abenzymes.com',NULL,NULL),
('ABB','Electrification & automation (industrial/energy)','https://global.abb/','https://careers.abb/finland/fi/home',TRUE),
('Ahlsell Oy','TBD','https://www.ahlsell.fi/',NULL,NULL),
('ALTEN Finland Oy','TBD','https://www.alten.fi/',NULL,NULL),
('Amplit Oy','TBD','https://www.amplit.fi/',NULL,NULL),
('ARE Oy','TBD','https://www.are.fi/',NULL,NULL),
('Arla Oy','TBD','https://www.arla.fi/',NULL,NULL),
('Beckhoff Automation Oy','TBD','https://www.beckhoff.com/fi-fi/',NULL,NULL),
('Bewi Raw','TBD','https://www.bewi.com/',NULL,NULL),
('Bluefors','Cryogenic measurement systems','https://bluefors.com/','https://careers.bluefors.com/',TRUE),
('Borealis Polymers Oy','TBD','https://www.borealisgroup.com/',NULL,NULL),
('Bosch Rexroth Oy','TBD','https://www.boschrexroth.com/fi/fi/',NULL,NULL),
('Bravida Finland Oy','TBD','https://www.bravida.fi/',NULL,NULL),
('Caverion Suomi Oy','Building services & industrial maintenance','https://www.caverion.com/','https://careers.caverion.com/',TRUE),
('Comatec Group','Engineering design & project services','https://www.comatec.fi/en/','https://career.comatec.fi/en-GB',TRUE),
('Convion','Fuel cell systems & hydrogen tech','https://convion.fi/','https://convion.fi/',TRUE),
('Creators Oy','TBD','https://www.creators.fi/',NULL,NULL),
('Destia Oy','TBD','https://www.destia.fi/',NULL,NULL),
('DNY Finland Oy','TBD','https://helsinkishipyard.fi/',NULL,NULL),
('Helsinki Shipyard','TBD','https://helsinkishipyard.fi/',NULL,NULL),
('Eaton Electric Oy','TBD','https://www.eaton.com/fi/fi-fi.html',NULL,NULL),
('Elomatic Consulting & Engineering Oy','TBD','https://www.elomatic.com/',NULL,NULL),
('Eltel Networks Oy','TBD','https://www.eltelnetworks.fi/',NULL,NULL),
('Emerson','TBD','https://www.emerson.com/fi-fi',NULL,NULL),
('Enersense International Oy','Energy & industrial services','https://enersense.com/','https://jobs.enersense.com/',TRUE),
('Enerz Oy','TBD','https://enerz.fi/',NULL,NULL),
('Metropolia hankkeet ja yhteistyöalustat','TBD','https://www.metropolia.fi/',NULL,NULL),
('Espoon Kaupunki','TBD','https://www.espoo.fi/',NULL,NULL),
('Etteplan Finland Oy','Engineering services & software/embedded','https://www.etteplan.com/','https://www.etteplan.com/careers/',TRUE),
('Fazer','TBD','https://www.fazer.com/',NULL,NULL),
('Fidelix Oy','Building automation & controls','https://www.fidelix.com/','https://www.fidelix.com/company/recruiting/',TRUE),
('Fingrid Oyj','Electricity transmission (TSO)','https://www.fingrid.fi/en/','https://tyopaikat.fingrid.fi/jobs',TRUE),
('Fortum Oy','Energy & utilities','https://www.fortum.com/','https://jobs.fortum.com/',TRUE),
('Franklin Oy','TBD','https://franklinoy.fi/',NULL,NULL),
('GA Telesis Engine Services Oy','TBD','https://www.gatelesis.com/',NULL,NULL),
('Granlund Oy','TBD','https://www.granlund.fi/',NULL,NULL),
('Greenlux Lighting Solutions Oy','TBD','https://greenlux.com/',NULL,NULL),
('Helsingin seudun ympäristöpalvelut HSY','TBD','https://www.hsy.fi/',NULL,NULL),
('HKFoods','TBD','https://www.hkfoods.com/',NULL,NULL),
('Honeywell Oy','TBD','https://www.honeywell.com/',NULL,NULL),
('Hyperion Robotics','Construction robotics / low-carbon infrastructure','https://www.hyperionrobotics.com/','https://hyperionrobotics.teamtailor.com/',TRUE),
('Inex Partners Oy','TBD','https://www.inex.fi/',NULL,NULL),
('Insplan Oy','TBD','https://insplan.fi/',NULL,NULL),
('INTEC Uusimaa Oy','TBD','https://intec.fi/',NULL,NULL),
('ISS Palvelut Oy','TBD','https://www.isspalvelut.fi/',NULL,NULL),
('JIS-Automation Oy','TBD','https://jis.fi/',NULL,NULL),
('Katko Oy','TBD','https://www.katko.com/',NULL,NULL),
('Kemira Oyj','TBD','https://www.kemira.com/',NULL,NULL),
('KLINGER Finland Oy','TBD','https://www.klinger.fi/',NULL,NULL),
('Konecranes','Lifting solutions & industrial cranes','https://www.konecranes.com/','https://konecranes.careers/',TRUE),
('Kreate Oy','TBD','https://kreate.fi/',NULL,NULL),
('LAPP Automaatio Oy','TBD','https://lappautomaatio.fi/',NULL,NULL),
('Legrand Finland Oy','TBD','https://www.legrand.fi/',NULL,NULL),
('Meconet Oy','TBD','https://www.meconet.net/',NULL,NULL),
('Metso','Process technology & mining','https://www.metso.com/','https://careers.metso.com/',TRUE),
('Mitsubishi Logisnext Europe Oy','TBD','https://logisnext.eu/',NULL,NULL),
('Neste Oyj','Renewable fuels & refining','https://www.neste.com/','https://jobs.neste.com/',TRUE),
('OiTec Oy','TBD','https://oitec.fi/',NULL,NULL),
('Omexom Suomi','TBD','https://www.omexom.fi/',NULL,NULL),
('Onninen Oy (Kesko Oyj)','TBD','https://www.onninen.fi/',NULL,NULL),
('Orion Pharma','TBD','https://www.orionpharma.com/',NULL,NULL),
('Oy Konwell Ab','TBD','https://www.konwell.fi/',NULL,NULL),
('Oy Nautor Ab','TBD','https://www.nautorswan.com/',NULL,NULL),
('Puolustus- ja Ilmailuteollisuus PIA ry','TBD','https://www.pia-ry.fi/',NULL,NULL),
('Pääkaupunkiseudun Kaupunkiliikenne Oy','TBD','https://kaupunkiliikenne.fi/',NULL,NULL),
('Ramboll','Engineering & consulting','https://www.ramboll.com/','https://www.ramboll.com/careers',TRUE),
('Rejlers Finland','Engineering consulting (energy/industry/buildings)','https://www.rejlers.com/fi/','https://career.rejlers.fi/',TRUE),
('RENSI Finlannd Oy','TBD','https://rensi.fi/',NULL,NULL),
('Sappi Kirkniemi','TBD','https://www.sappi.com/',NULL,NULL),
('Schneider Electric','Energy management & automation','https://www.se.com/fi/fi/','https://www.se.com/fi/fi/about-us/careers/overview/',TRUE),
('SESKO ry Sähkötekniset standardit Suomessa','TBD','https://sesko.fi/',NULL,NULL),
('Siemens Energy Oy','Energy technology (power generation, grids)','https://www.siemens-energy.com/global/en.html','https://jobs.siemens-energy.com/en_US/CareersMarketplace/Jobs',TRUE),
('Siemens Osakeyhtiö','Industrial tech & digitalization','https://www.siemens.com/fi/fi.html','https://www.siemens.com/global/en/company/jobs.html',TRUE),
('Sinebrychoff','TBD','https://sinebrychoff.fi/',NULL,NULL),
('Sitowise','TBD','https://sitowise.com/',NULL,NULL),
('SMC Automation Oy','TBD','https://www.smc.eu/fi-fi',NULL,NULL),
('Sonepar Suomi Oy','TBD','https://www.sonepar.fi/',NULL,NULL),
('Starship Technologies Oy','Autonomous delivery robots','https://www.starship.xyz/','https://starship.teamtailor.com/jobs',TRUE),
('Sweco Finland Oy','Engineering & architecture consulting','https://www.sweco.fi/en/','https://www.sweco.fi/en/career/',TRUE),
('Sähkölandia','TBD','https://www.sahkolandia.fi/',NULL,NULL),
('Tikkurila Oyj','TBD','https://tikkurila.com/',NULL,NULL),
('Vaisala Oyj','Environmental measurement & weather tech','https://www.vaisala.com/','https://careers.vaisala.com/',TRUE),
('Valmet','Process tech, automation & services (pulp/energy)','https://www.valmet.com/','https://www.valmet.com/careers/',TRUE),
('WITRON','TBD','https://www.witron.com/',NULL,NULL),
('WSP','Engineering & consulting','https://www.wsp.com/','https://rekry.wsp.com/jobs',TRUE),
('A-Katsastus Oy','TBD','https://www.a-katsastus.fi/',NULL,NULL),
('Autokeskus Oy','TBD','https://www.autokeskus.fi/',NULL,NULL),
('Bilia Oy Ab','TBD','https://www.bilia.fi/',NULL,NULL),
('CityKatsastus Oy','TBD','https://www.citykatsastus.fi/',NULL,NULL),
('Diagno Finland Oy','TBD','https://diagno.fi/',NULL,NULL),
('Hedin Automotive Finland Oy','TBD','https://www.hedinautomotive.fi/',NULL,NULL),
('K-Auto & Porsche','TBD','https://www.k-auto.fi/',NULL,NULL),
('Oy Sisu Auto Ab','TBD','https://sisuauto.com/',NULL,NULL),
('Plus Katsastus Oy','TBD','https://plus.fi/',NULL,NULL),
('Pohjolan Liikenne Ab','TBD','https://pl.fi/',NULL,NULL),
('Roadster Finland Oy - Tesla','TBD','https://www.tesla.com/fi_fi',NULL,NULL),
('Skoda Brand Store / Helkama-Autokauppa Oy','TBD','https://skodabrandstore.fi/',NULL,NULL),
('Suomen Katsastusasemat Oy','TBD','https://suomenkatsastusasemat.fi/',NULL,NULL),
('VDL Bus & Coach Finland Oy','TBD','https://www.vdlbuscoach.com/',NULL,NULL),
('Veho Oy Ab','TBD','https://www.veho.fi/',NULL,NULL),
('Volvo Finland Ab','TBD','https://www.volvotrucks.fi/',NULL,NULL);
